LIB_DIR = @CMAKE_CURRENT_SOURCE_DIR@
INC_DIR = @CMAKE_CURRENT_SOURCE_DIR@/src
MY_CXX_FLAGS=@CMAKE_CXX_FLAGS@
MY_CXX_OPT_FLAGS=@CMAKE_CXX_OPT_FLAGS@
MY_CXX=@CMAKE_CXX_COMPILER@
MY_CC=@CMAKE_C_COMPILER@